stages:
  - name: Build
    steps:
      - runScriptConfig:
          image: maven:3-openjdk-17
          shellScript: mvn package -DskipTests
  - name: Build Docker with DIND
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: docker.dev.folio.org/mod-bulk-operations:firebird-latest
          pushRemote: true
          registry: docker.dev.folio.org
  - name: Deploy
    steps:
      - applyAppConfig:
          catalogTemplate: p-ngvqv:firebird-helmcharts-mod-bulk-operations
          version: 0.1.30
          answers:
            image.repository: docker.dev.folio.org/mod-bulk-operations
            image.tag: firebird-latest
            postJob.enabled: true
          targetNamespace: firebird
          name: mod-bulk-operations
timeout: 60
notification: {}
