openapi: 3.0.0
info:
  title: Bulk operations API
  version: v1
  description: Bulk operations API

servers:
  - url: /to-be-changed/

paths:
  /to-be-changed:
    get:
      operationId: getExample
      description: example endpoint to generate api doc
      responses:
        '200':
          description: 'example endpoint result to generate api doc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/searchResult'

components:
  schemas:
    operationType:
      $ref: 'schemas/operation_type.json#/OperationType'
    entityType:
      $ref: 'schemas/entity_type.json#/EntityType'
    entityCustomIdentifierType:
      $ref: 'schemas/entity_custom_identifier_type.json#/EntityCustomIdentifierType'
    operationStatusType:
      $ref: 'schemas/operation_status_type.json#/OperationStatusType'
    statusType:
      $ref: 'schemas/status_type.json#/StatusType'
    stateType:
      $ref: 'schemas/state_type.json#/StateType'
    updateOptionType:
      $ref: 'schemas/update_option_type.json#/UpdateOptionType'
    updateActionType:
      $ref: 'schemas/update_action_type.json#/UpdateActionType'
    searchResult:
      type: object
      properties:
        record:
          type: object
          description: Example response

