ALTER TYPE UpdateOptionType ADD VALUE IF NOT EXISTS 'ITEM_NOTE';
ALTER TYPE UpdateOptionType ADD VALUE IF NOT EXISTS 'CHECK_IN_NOTE';
ALTER TYPE UpdateOptionType ADD VALUE IF NOT EXISTS 'CHECK_OUT_NOTE';
ALTER TYPE UpdateOptionType ADD VALUE IF NOT EXISTS 'ADMINISTRATIVE_NOTE';
