ALTER TYPE UpdateOptionType ADD VALUE 'ITEM_NOTE';
ALTER TYPE UpdateOptionType ADD VALUE 'CHECK_IN_NOTE';
ALTER TYPE UpdateOptionType ADD VALUE 'CHECK_OUT_NOTE';
ALTER TYPE UpdateOptionType ADD VALUE 'ADMINISTRATIVE_NOTE';
