ALTER TYPE UpdateActionType ADD VALUE IF NOT EXISTS 'MARK_AS_STAFF_ONLY';
ALTER TYPE UpdateActionType ADD VALUE IF NOT EXISTS 'REMOVE_MARK_AS_STAFF_ONLY';
ALTER TYPE UpdateActionType ADD VALUE IF NOT EXISTS 'REMOVE_ALL';
ALTER TYPE UpdateActionType ADD VALUE IF NOT EXISTS 'CHANGE_TYPE';
