ALTER TYPE UpdateOptionType ADD VALUE IF NOT EXISTS 'ELECTRONIC_ACCESS_URL_RELATIONSHIP';
ALTER TYPE UpdateOptionType ADD VALUE IF NOT EXISTS 'ELECTRONIC_ACCESS_URI';
ALTER TYPE UpdateOptionType ADD VALUE IF NOT EXISTS 'ELECTRONIC_ACCESS_LINK_TEXT';
ALTER TYPE UpdateOptionType ADD VALUE IF NOT EXISTS 'ELECTRONIC_ACCESS_MATERIALS_SPECIFIED';
ALTER TYPE UpdateOptionType ADD VALUE IF NOT EXISTS 'ELECTRONIC_ACCESS_URL_PUBLIC_NOTE';
