ALTER TABLE bulk_operation ADD COLUMN IF NOT EXISTS fql_query_id UUID;
ALTER TABLE bulk_operation ADD COLUMN IF NOT EXISTS fql_query TEXT;

ALTER TYPE OperationStatusType ADD VALUE IF NOT EXISTS 'EXECUTING_QUERY';
ALTER TYPE OperationStatusType ADD VALUE IF NOT EXISTS 'RETRIEVING_IDENTIFIERS';
ALTER TYPE OperationStatusType ADD VALUE IF NOT EXISTS 'SAVED_IDENTIFIERS';
